### ISSUE TITLE
no access to make PR to update to latest version 94, can someone do this?

### ISSUE THREAD

**Issue by Dinoraptor101** [webdriverio-community/node-edgedriver#12]
There's an appetite to get maintained with the latest version of Edge, as it is becoming a more prominent browser in the corporate world.
The current version at the time of this writing is 94, I have tested the changes locally, and the following are the only required changes.
---
- add the latest binary from the official URL: [Developer Microsoft, WebDriver](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/)
   - bin\
   - lib\msedgedriver\
- update the corresponding version in the JS file:  
   - lib\msedgedriver.js

**Comment by christian-bromann** [comment]
Closing as the issue got out of date. I've rewritten how the driver works, please try and let me know if you still experience any issues.
